### ISSUE TITLE
Help with following ffmpeg command line

### ISSUE THREAD

**Issue by owaineevans** [phaux/node-ffmpeg-stream#10]
Hi,

Firstly my knowledge of nodejs and javascript is not that great, so apologies if I'm doing something stupid!

I've got the following ffmpeg command-line which works fine, and I want to use it to get an mjpeg stream into my nodejs code:

`ffmpeg -i 'rtsp:/192.168.100.103:554/cam/realmonitor?channel=1&subtype=0' -codec:v copy -bsf:v mjpeg2jpeg img%03d.jpg`

I assumed I could use the following code:

```
const ffmpeg = require('ffmpeg-stream').ffmpeg;

const convertor = ffmpeg();

convertor.input('rtsp://admin:adminadmin1@192.168.100.103:554/cam/realmonitor?channel=1&subtype=0', { f: 'mjpeg', vcodec: 'copy' }).pipe(process.stdout);
```
I'm getting an exception in util.js in line 320 which I don't fully understand:

```
Exception has occurred: Error
Error
    at Object.<anonymous> (/home/owaine/workspace/nodejs/security2/node_modules/bluebird/js/main/util.js:320:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/home/owaine/workspace/nodejs/security2/node_modules/bluebird/js/main/promise.js:13:12)
    at Object.<anonymous> (/home/owaine/workspace/nodejs/security2/node_modules/bluebird/js/main/bluebird.js:9:39)
```

Can anyone help?

**Comment by phaux** [comment]
1. The arguments you typed in the command-line aren't exactly the same as the ones in JS.
2. These arguments should be specified for the output, not input.
3. You can't pipe an input anywhere, it's a writable stream.
4. You don't even call `run`.

Try this:

```js
const conv = ffmpeg()
conv.input('rtsp://…')
conv.output({f: 'image2pipe', vcodec: 'mjpeg'}).pipe(process.stdout)
conv.run()
```

**Comment by owaineevans** [comment]
Thanks for the rapid response.

My code crashed before the `run()` so I didn't bother including it.

I've investigated further and it might be something with my packages. 
Any call to conv.input() or conv.output() seems to cause the same error in `bluebird/js/main/util.js`

line 320 - `try {throw new Error(); } catch (e) {ret.lastLineError = e;}`

I'm running Node.js v6.11.4 on Ubuntu 17.04 with bluebird 2.9.34

npm list reports:
```
├─┬ ffmpeg-stream@0.5.0
│ ├── bluebird@2.9.34
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ └─┬ tmp@0.0.26
│   └── os-tmpdir@1.0.2
```
ffmpeg -version reports:

```
$ ffmpeg -version
ffmpeg version 3.3.4-2 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 7 (Ubuntu 7.2.0-8ubuntu2)
configuration: --prefix=/usr --extra-version=2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 58.100 / 55. 58.100
libavcodec     57. 89.100 / 57. 89.100
libavformat    57. 71.100 / 57. 71.100
libavdevice    57.  6.100 / 57.  6.100
libavfilter     6. 82.100 /  6. 82.100
libavresample   3.  5.  0 /  3.  5.  0
libswscale      4.  6.100 /  4.  6.100
libswresample   2.  7.100 /  2.  7.100
libpostproc    54.  5.100 / 54.  5.100
```

**Comment by owaineevans** [comment]
Hi, thanks for all your help!

Everything is working perfectly :)
