### ISSUE TITLE
Error : write EPIPE 

### ISSUE THREAD

**Issue by subhamAggarwal** [phaux/node-ffmpeg-stream#14]
```js
const { Converter } = require("ffmpeg-stream")
const { createReadStream, createWriteStream } = require("fs");
const AwsSdk = require('aws-sdk');
const { PassThrough } = require('stream')
const { aws } = require('./config');
AwsSdk.config.update({
    accessKeyId: aws.accessKeyId,
    secretAccessKey: aws.secretAccessKey,
    region: aws.region
});
const bucket = new AwsSdk.S3({ params: { Bucket: aws.bucket } });

function uploadFromStream(resolve) {
    var pass = new PassThrough();
    bucket.upload({ Body: pass, Key: 'out2.mp4' }, function (err, data) {
        console.log(`end : ${Date.now()}`)
        console.log(err, data);
        resolve()
    });
    return pass;
}


module.exports = imagesStreams => {
    return new Promise((resolve, reject) => {
        let conv = new Converter();
        const input = conv.createInputStream({ f: 'image2pipe', r: 25 }) // create input writable stream
        //conv.createOutputToFile('out.mp4', { vcodec: 'libx264', pix_fmt: 'yuv420p' })

        conv
            .output({
                f: 'mp4', vcodec: 'libx264', pix_fmt: 'yuv420p', buffer: true
            })
            .pipe(uploadFromStream(resolve))
            .on('error',err=>{
                console.log("error is after event stream",err);
            })

        // for every frame create a function that returns a promise
        imagesStreams.map(stream => () =>
            new Promise((fulfill, reject) =>
                stream
                    .on('end', fulfill)
                    .on('error', reject)
                    .pipe(input, { end: false })
            )
        )
            .reduce((prev, next) => prev.then(next), Promise.resolve())
            .then(() => {
                input.end();
                console.log("End of input");
            })
            .catch(reject)
        conv.run()
        .then(() => console.log(`Conversion completed`))
        .catch(err => console.error(`Conversion failed: ${err}`))
    })

}
```

I am facing 
```js
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
Emitted 'error' event at:
    at Socket.onerror (_stream_readable.js:713:12)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:604:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:781:10)

```

I am running ffmpeg on linux then getting this error 
this code is working on mac

why this is happening?

**Comment by phaux** [comment]
Maybe it has something to do with how linux pipes work. Try googling the error message. I don't think this is related to this library

**Comment by venkatesh-rao** [comment]
I faced the same issue and did a **fix**.

``` 
// for every frame create a function that returns a promise
imagesStreams.map((stream, index) => {
  const end = index === imagesStreams.length - 1; // <---- end your input at the last imagesStream
  return () => 
    new Promise((fulfill, reject) =>
        stream
            .on('end', fulfill)
            .on('error', reject)
            .pipe(input, { end }) // <---- end your input at the last imagesStream
    )
})
