### ISSUE TITLE
Unable to pipe in multiple input GIFs

### ISSUE THREAD

**Issue by marcusteh1238** [phaux/node-ffmpeg-stream#28]
I'm trying to pass in 2 GIFs through the input stream, and then overlay one over the other. Both GIFs have the same dimensions and FPS.
I'm essentially trying to replicate the following command, which currently works on ffmpeg:
```bash
ffmpeg -y -i input1.gif -i input2.gif -lavfi "[0][1]overlay" out.gif
```
Here are the input files, and expected output file.
[input1.gif](https://user-images.githubusercontent.com/50549441/99544609-76ae7780-29ef-11eb-9157-08a7d461356b.gif)
[input2.gif](https://user-images.githubusercontent.com/50549441/99544666-875eed80-29ef-11eb-9fd8-a4b1a9b2bfd7.gif)
[out.gif](https://user-images.githubusercontent.com/50549441/99545059-f3415600-29ef-11eb-83e6-43fa4357fb53.gif)
Here is my code snippet:
```js
const gifBufferArray = [buffer1, buffer2]; // array of 2 gif buffers
const converter = new Converter();
const input = converter.createInputStream({
    f: "gif_pipe",
    lavfi: "[0][1]overlay"
});
converter.createOutputToFile(path.resolve('./out.gif'), { f: "gif" });

gifBufferArray
    .map(buffer => new Promise(res => input.write(buffer, res)))
    .reduce((prev, next) => prev.then(next), Promise.resolve())
    .then(input.end())
    .then(converter.run())
```
This error is produced when I run the code:
```
Error: Converting failed
  Input #0, gif_pipe, from 'pipe:3':
    Duration: N/A, bitrate: N/A
      Stream #0:0: Video: gif, bgra, 200x246, 25 fps, 25 tbr, 25 tbn, 25 tbc
  Invalid file index 1 in filtergraph description [0][1]overlay.
    at ChildProcess.<anonymous> (D:\repo\node_modules\ffmpeg-stream\lib\index.js:281:24)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```
It seems that FFMPEG does not recognize that the first GIF has ended and the second one has begun, taking the whole stream as a singular GIF. Is there a way to fix or work around this?

**Comment by marcusteh1238** [comment]
Oh I figured it out, I could just create multiple input streams as such and it works.
```js
const input1 = converter.createInputStream({
    f: "gif"
});
const input2 = converter.createInputStream({
    f: "gif",
    lavfi: "[0][1]overlay"
});
input1.write(buffer1);
input2.write(buffer2);
```
