### ISSUE TITLE
How to read an mp4 video

### ISSUE THREAD

**Issue by hbj** [phaux/node-ffmpeg-stream#44]
I'm trying to read an mp4 video and just write is as is through the stream interfaces but I'm getting an error. Doing the same thing on the command line with `ffmpeg -f mp4 -i test.mp4 test_out.mp4` works just fine. Any help is very appreciated, Thanks.

Code:

```js
const { Converter } = require("ffmpeg-stream");
const { createReadStream, createWriteStream } = require("fs");

async function convert() {
  const converter = new Converter();

  const converterInput = converter.createInputStream({
    f: "mp4",
  });
  createReadStream(`${__dirname}/test.mp4`).pipe(converterInput);

  const converterOutput = converter.createOutputStream({
    f: "mp4",
  });
  converterOutput.pipe(createWriteStream(`${__dirname}/test_out.mp4`));

  // start processing
  await converter.run();
}

convert()
  .then(() => console.log("done."))
  .catch((err) => console.error(err));
```

Error:

```
Error: Converting failed
  [mov,mp4,m4a,3gp,3g2,mj2 @ 0x564e1f7c3e40] stream 1, offset 0x2c: partial file
  [mov,mp4,m4a,3gp,3g2,mj2 @ 0x564e1f7c3e40] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1280x720, 727 kb/s): unspecified pixel format
  Consider increasing the value for the 'analyzeduration' and 'probesize' options
  Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'pipe:3':
    Metadata:
      major_brand     : mp42
      minor_version   : 1
      compatible_brands: mp41mp42isom
      creation_time   : 2018-04-25T19:38:16.000000Z
    Duration: 00:00:30.76, start: 0.000000, bitrate: N/A
      Stream #0:0(und): Video: h264 (avc1 / 0x31637661), none, 1280x720, 727 kb/s, 23.98 fps, 24 tbr, 90k tbn, 180k tbc (default)
      Metadata:
        creation_time   : 2018-04-25T19:38:16.000000Z
        handler_name    : Core Media Video
      Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 47 kb/s (default)
      Metadata:
        creation_time   : 2018-04-25T19:38:16.000000Z
        handler_name    : Core Media Audio
  Stream mapping:
    Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
    Stream #0:1 -> #0:1 (aac (native) -> aac (native))
  [mov,mp4,m4a,3gp,3g2,mj2 @ 0x564e1f7c3e40] stream 1, offset 0x2c: partial file
  pipe:3: Invalid data found when processing input
  Cannot determine format of input stream 0:0 after EOF
  Error marking filters as finished
  Conversion failed!
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/ffmpeg-stream/lib/index.js:281:24)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
```

**Comment by phaux** [comment]
The actual command it runs is more like `ffmpeg -i - < test.mp4 > test_out.mp4` and it fails because mp4 doesn't like being piped.

Run your program with `DEBUG=ffmpeg-stream` env var to see what exactly the command looks like.

**Comment by hbj** [comment]
@phaux Thanks for the details!

I did some more tests and found out it only fails if the output format is set to mp4. Setting the input format to mp4 and the output format to e.g. webm woks perfectly.

I'm actually streaming from files for testing purposes, the final solution will stream from/to network streams.
